<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.9</version>
		<relativePath/>
	</parent>

	<groupId>com.tuzhan</groupId>
	<artifactId>tuzhan</artifactId>
	<version>1.0.0</version>
	<name>tuzhan</name>
	<description>tuzhan</description>

	<properties>
		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.build.finalName>tuzhan-web-${project.version}</project.build.finalName>
		<dollar>$</dollar>
		<jdk.version>17.0.19</jdk.version>
		<jdk.classifier></jdk.classifier> <!-- 空表示oracle官方的，bisheng_ 表示毕昇的 -->
	</properties>

	<dependencies>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.21.0</version>
		</dependency>

		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.6.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.19.0</version>
		</dependency>

		<!--<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.11.0</version>
		</dependency>-->

		<!--<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-digester3</artifactId>
			<version>3.2</version>
		</dependency>-->

		<!--<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.5.0</version>
		</dependency>-->

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>32.1.3-jre</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>failureaccess</artifactId>
			<version>1.0.3</version>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.12.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>

		<!--<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-graphql</artifactId>
		</dependency>-->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>com.clickhouse</groupId>
			<artifactId>clickhouse-jdbc</artifactId>
			<version>0.9.8</version>
			<classifier>all</classifier>
		</dependency>

		<!-- 高精度多边形处理 -->
		<dependency>
			<groupId>org.locationtech.jts</groupId>
			<artifactId>jts-core</artifactId>
			<version>1.20.0</version>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.7.13</version>
		</dependency>

		<dependency>
			<groupId>com.gdk</groupId>
			<artifactId>gdk-db3</artifactId>
			<version>3.9.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/gdk-db3-3.9.0.jar</systemPath>
		</dependency>

		<!-- 用于日期格式的自动检测解析 -->
		<dependency>
			<groupId>com.github.sisyphsu</groupId>
			<artifactId>dateparser</artifactId>
			<version>1.0.11</version>
			<exclusions>
				<exclusion>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-yaml</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<finalName>${project.build.finalName}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>

			<!-- maven构建前端node编译打包 -->
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>1.15.4</version>
				<configuration>
					<workingDirectory>${basedir}</workingDirectory>
					<installDirectory>${basedir}</installDirectory>
					<skipTests>true</skipTests>
					<npmRegistryURL>https://registry.npmmirror.com/</npmRegistryURL>
					<environmentVariables>
						<!-- unit: MB
                            max-semi-space-size: 此标志控制 V8 堆中 “新空间” 的大小，“新空间”用于分配新创建的对象，并频繁地进行垃圾回收。
                            max-old-space-size: 此标志限制了 V8 堆中旧空间的大小，旧空间用于存储长期存活的对象。
                        -->
						<NODE_OPTIONS>--max-old-space-size=4096 --max-semi-space-size=1024</NODE_OPTIONS>
					</environmentVariables>
				</configuration>
				<executions>
					<execution>
						<id>install_node_npm</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v22.18.0</nodeVersion>
							<npmVersion>10.9.3</npmVersion>
							<!--
                            <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
                            <npmDownloadRoot>https://registry.npmjs.org/npm/-/</npmDownloadRoot>
                            -->
						</configuration>
					</execution>

					<execution>
						<id>npm_install</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>

					<execution>
						<id>npm_run_build</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>run build</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>3.2.0</version>
				<executions>
					<execution>
						<id>ant-copy-files</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<!-- 拷贝到 target/classes/static/ 目录下 -->
								<delete dir="${project.build.outputDirectory}/static/assets"/>
								<copy todir="${project.build.outputDirectory}/static" overwrite="true" encoding="UTF-8">
									<fileset dir="${basedir}/src/frontend/dist">
										<include name="assets/**"/>
										<!--<include name="index.html" />-->
										<include name="favicon.ico" />
										<include name="favicon.svg" />
										<include name="favicon.png" />
									</fileset>
								</copy>
								<copy todir="${project.build.outputDirectory}/templates" overwrite="true" encoding="UTF-8">
									<fileset dir="${basedir}/src/frontend/dist">
										<include name="index.html" />
									</fileset>
								</copy>
								<replace file="${project.build.outputDirectory}/templates/index.html"
										 propertyFile="${basedir}/src/main/resources/application.properties">
									<replacefilter>
										<replacetoken><![CDATA[<html>]]></replacetoken>
										<replacevalue><![CDATA[<html xmlns:th="http://www.thymeleaf.org">]]></replacevalue>
									</replacefilter>
									<replacefilter>
										<replacetoken><![CDATA[</head>]]></replacetoken>
										<replacevalue><![CDATA[<script th:inline="javascript">window.APP_BASE_URL="[(${contextPath})]";</script></head>]]></replacevalue>
									</replacefilter>
									<replacefilter>
										<replacetoken><![CDATA[src="/]]></replacetoken>
										<replacevalue><![CDATA[src="]]></replacevalue>
									</replacefilter>
									<replacefilter>
										<replacetoken><![CDATA[href="/]]></replacetoken>
										<replacevalue><![CDATA[href="]]></replacevalue>
									</replacefilter>
									<replacefilter>
										<replacetoken><![CDATA[<script>]]></replacetoken>
										<replacevalue><![CDATA[<script th:inline="javascript">]]></replacevalue>
									</replacefilter>
									<replacefilter>
										<replacetoken><![CDATA[<head>]]></replacetoken>
										<replacevalue><![CDATA[<head><base th:href="@{/}">]]></replacevalue>
									</replacefilter>
								</replace>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<!--<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.3.0</version>
				<executions>
					<execution>
						<id>copy-jdk</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/tmp</outputDirectory>
							<artifactItems>
								<artifactItem>
									<groupId>openjdk</groupId>
									<artifactId>jdk-linux</artifactId>
									<version>${jdk.version}</version>
									<classifier>${jdk.classifier}x64</classifier>
									<type>tar.gz</type>
								</artifactItem>

								<artifactItem>
									<groupId>openjdk</groupId>
									<artifactId>jdk-linux</artifactId>
									<version>${jdk.version}</version>
									<classifier>${jdk.classifier}aarch64</classifier>
									<type>tar.gz</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.4.2</version>
				<executions>
					<execution>
						<id>make-assembly-linux</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<appendAssemblyId>true</appendAssemblyId>
							<runOnlyAtExecutionRoot>false</runOnlyAtExecutionRoot>
							<outputDirectory>${project.build.directory}</outputDirectory>
							<descriptors>
								<descriptor>${basedir}/package-web-assembly-linux-x86_64.xml</descriptor>
								<descriptor>${basedir}/package-web-assembly-linux-aarch64.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>-->

		</plugins>
	</build>

</project>
