spring.application.name=Tuzhan
spring.time-zone=Asia/Shanghai

server.port=9090
#server.servlet.context-path=

#server.error.whitelabel.enabled=false
#server.error.path=/user-error
server.error.include-exception=true
server.error.include-stacktrace=always

# Tomcat
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.accept-count=1000
server.tomcat.threads.max=500
server.tomcat.threads.min-spare=10
server.tomcat.connection-timeout=30000
server.tomcat.basedir=${user.dir}/logs
server.tomcat.accesslog.enabled=false
server.tomcat.accesslog.directory=${user.dir}/logs
server.tomcat.accesslog.pattern=%t %a %r %s %D
server.tomcat.accesslog.file-date-format=yyyy-MM-dd
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.rotate=true

# SSL
server.ssl.enabled=false
server.ssl.key-store=classpath:ssl_test.p12
# jks or PKCS12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=aip@2025
# 可以通过 keytool -list -v -keystore ./ssl_test.p12 -storetype PKCS12 查看别名
#server.ssl.key-alias=aipgateway
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA


# 文件上传配置
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${user.dir}/uploads
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=50MB
# 设置为0，启用直接流式上传
spring.servlet.multipart.file-size-threshold=0

# thymeleaf config
spring.mvc.static-path-pattern=/assets/**
spring.web.resources.static-locations=classpath:/assets/
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8